const stages = [
 {key:'vibe',title:'What are we feeling?',choices:[['cozy','🕯️','Cozy (only allowed if still sick)','Slow down and get comfortable'],['adventurous','🌿','Adventurous','Something out of the ordinary'],['romantic','🌷','Laid-back','Take it easy, enjoy the moment'],['playful','🎯','Playful','Laughs and friendly competition']]},
 {key:'activity',title:'How shall we spend our time?',choices:[['outside','☀️','Fresh air','Walks and little escapes'],['creative','🎨','Indoor Activities','Something fun indoors'],['explore','🗺️','Explore (probably need a car)','Discover somewhere new'],['home','🏡','Stay in','Our own little world']]},
 {key:'food',title:'And something delicious?',choices:[['vegan','🌱','Dinner out vegan','A delicious plant-based dinner'],['picnic','🧺','Pack a picnic','Something tasty to take along'],['dinner','🍽️','Dinner out','Feeling non-vegan today'],['coffee','☕','Coffee & treats','A sip and something sweet']]},
 {key:'ending',title:'One last lovely thing…',choices:[['sunset','🌅','Sunset & evening stroll','Take a walk and catch the sunset'],['movie','🎬','A movie','Get comfortable together'],['custom','✨','I have my own idea','Tell me what you have in mind']]}
];
const food={vegan:'Dinner out vegan',picnic:'a packed picnic',dinner:'Dinner out (feeling non-vegan today)',coffee:'coffee and a sweet treat'};
const foodPlan=()=>`Food options: ${picks.food.map(value=>food[value]).join(' / ')}.`;
const ending={sunset:'We will take an evening stroll and catch the sunset.',movie:'We will end with a movie.'};
const escapeHtml=value=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const endingPlan=()=>picks.ending.map(value=>value==='custom'?`Your idea: ${escapeHtml(picks.endingIdea.trim())}`:ending[value]).join(' ');
let cheekyAttempts=0;
const app=document.querySelector('#app');let step=0,picks={},matches=[],ratings=[],index=0;
const label=k=>{const choices=stages.find(s=>s.key===k).choices;return (k==='food'||k==='ending'?(picks[k]||[]):[picks[k]]).map(value=>choices.find(c=>c[0]===value)[2]).join(', ');};
const isSelected=(key,value)=>key==='food'||key==='ending'?(picks[key]||[]).includes(value):picks[key]===value;
const hasSelection=key=>key==='food'?Boolean(picks.food?.length):key==='ending'?Boolean(picks.ending?.length) && (!isSelected('ending','custom') || Boolean(picks.endingIdea?.trim())):Boolean(picks[key]);
const chips=()=>`<div class="chips">${stages.map(s=>`<span class="chip">${label(s.key)}</span>`).join('')}</div>`;
function focusHeading(){app.querySelector('h1').focus();}
function rankIdeas(p){
 const activities=ideas.filter(idea=>idea.category==='activity' && idea.activity===p.activity && (idea.activity!=='home'||p.vibe==='cozy')).sort((a,b)=>Number(b.vibes.includes(p.vibe))-Number(a.vibes.includes(p.vibe)));
 const foods=ideas.filter(idea=>idea.category==='food' && idea.food.some(value=>p.food.includes(value)));
 const endings=ideas.filter(idea=>idea.category==='ending' && idea.ending.some(value=>p.ending.includes(value)));
 return [...activities,...foods,...endings];
}
const assetUrl=path=>encodeURI(path);
const categoryLabel=idea=>({activity:'Activity idea',food:'Food stop',ending:'To finish the day'}[idea.category]);
function ideaDetails(idea){return `<p class="location">${escapeHtml(idea.location)}</p><div class="venue-links">${idea.source && idea.id!=='sugarmama'?`<a href="${idea.source}" target="_blank" rel="noopener noreferrer">Website & details &#8599;</a>`:''}${idea.source?`<a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(idea.title+' '+idea.location)}" target="_blank" rel="noopener noreferrer">Open map &#8599;</a>`:''}${idea.menu?`<a href="${idea.menu}" target="_blank" rel="noopener noreferrer">Menu &#8599;</a>`:''}</div>${idea.extras?.length?`<details class="route-details"><summary>Our saved route & map</summary>${idea.extras.map(path=>`<a href="${assetUrl(path)}" target="_blank" rel="noopener noreferrer"><img src="${assetUrl(path)}" alt="Saved route or map for ${escapeHtml(idea.title)}" loading="lazy"></a>`).join('')}</details>`:''}`;}


function playfulChoices(){return `<section class="cheeky-panel" aria-label="A little friendly competition"><h2>Oh, feeling competitive?</h2><p>Pick your side. One of these has a mind of its own.</p><button id="ready" class="primary" aria-pressed="${picks.challenge==='ready'}">Be ready to lose &#128540;</button><div class="chase-arena"><button id="winning" class="primary" aria-pressed="${picks.challenge==='winning'}">I'm winning &#128527;</button></div><p id="tease" role="status">${picks.challenge?"Challenge accepted. Let's see about that!":'Go on, make your claim.'}</p></section>`;}
function wirePlayful(){
 const winning=app.querySelector('#winning'),arena=app.querySelector('.chase-arena');
 let blockClick=false,resetTimer;
 const choose=value=>{picks.challenge=value;build();app.querySelector(value==='ready'?'#ready':'#winning').focus();};
 app.querySelector('#ready').onclick=()=>choose('ready');
 const dodge=event=>{
  if(blockClick || cheekyAttempts>=5 || (event.type==='pointerenter' && event.pointerType!=='mouse'))return false;
  cheekyAttempts++;blockClick=true;clearTimeout(resetTimer);resetTimer=setTimeout(()=>{blockClick=false;},500);
  const maxX=Math.max(0,arena.clientWidth-winning.offsetWidth),maxY=Math.max(0,arena.clientHeight-winning.offsetHeight);
  winning.style.left=(cheekyAttempts%2===1?maxX:0)+'px';
  winning.style.top=(cheekyAttempts===2?0:maxY)+'px';
  app.querySelector('#tease').textContent=['Almost! Winning is harder than it looks.','Too slow! Still feeling confident?','You will have to be quicker than that!','One more try. I believe in you... maybe.','Okay, okay. You can catch me now.'][cheekyAttempts-1];
  return true;
 };
 winning.onpointerenter=dodge;
 winning.onpointerdown=event=>{if(blockClick || dodge(event)){event.preventDefault();}};
 winning.onclick=event=>{if(event.detail!==0 && (blockClick || dodge(event))){event.preventDefault();return;}choose('winning');};
}

function build(){const s=stages[step];app.innerHTML=`<span class="eyebrow">A little plan for the weekend</span><h1 tabindex="-1">${step===0?'Hey Ines, what shall we do?':s.title}</h1><p>${s.key==='food'||s.key==='ending'?'Pick one or more options. Tap again to deselect.':'Pick whatever suits your mood. Then see which ideas sound fun.'}</p><div class="steps" aria-label="Step ${step+1} of 4">${stages.map((_,i)=>`<span class="${i<=step?'done':''}"></span>`).join('')}</div><div class="meta">0${step+1} / 04 · ${s.key.toUpperCase()}</div>${step===0?`<h2>${s.title}</h2>`:''}<div class="options">${s.choices.map(([value,icon,title,detail])=>`<button class="option ${isSelected(s.key,value)?'selected':''}" data-choice="${value}" ${s.key==='activity' && value==='home' && picks.vibe!=='cozy'?'disabled':''} aria-pressed="${isSelected(s.key,value)}"><span class="icon" aria-hidden="true">${icon}</span><span><strong>${title}</strong><small>${s.key==='activity' && value==='home' && picks.vibe!=='cozy'?'Only available with the Cozy vibe':detail}</small></span></button>`).join('')}</div>${step===0 && picks.vibe==='playful'?playfulChoices():''}${s.key==='ending' && isSelected('ending','custom')?'<div class="own-idea"><label for="ending-idea">What is your idea?</label><textarea id="ending-idea" maxlength="500" placeholder="I was thinking we could..."></textarea></div>':''}<div class="actions"><button id="back" class="text-button" ${step===0?'hidden':''}>← Back</button><button id="next" class="primary" ${!hasSelection(s.key)||(step===0 && picks.vibe==='playful' && !picks.challenge)?'disabled':''}>${step===3?'Find our ideas':'Next little choice'} →</button></div>`;
app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(s.key==='activity' && b.dataset.choice==='home' && picks.vibe!=='cozy')return;if(s.key==='food'||s.key==='ending'){const selected=picks[s.key]||[];picks[s.key]=selected.includes(b.dataset.choice)?selected.filter(value=>value!==b.dataset.choice):[...selected,b.dataset.choice];}else{picks[s.key]=b.dataset.choice;}if(s.key==='vibe'){delete picks.challenge;cheekyAttempts=0;if(picks.vibe!=='cozy' && picks.activity==='home')delete picks.activity;}build();app.querySelector(`[data-choice="${b.dataset.choice}"]`).focus();});if(s.key==='ending' && isSelected('ending','custom')){const field=app.querySelector('#ending-idea');field.value=picks.endingIdea||'';field.oninput=()=>{picks.endingIdea=field.value;app.querySelector('#next').disabled=!hasSelection('ending');};}if(step===0 && picks.vibe==='playful')wirePlayful();app.querySelector('#back').onclick=()=>{step--;build();focusHeading();};app.querySelector('#next').onclick=()=>{if(!hasSelection(s.key)||(step===0 && picks.vibe==='playful' && !picks.challenge))return;if(step<3){step++;build();}else{matches=rankIdeas(picks);ratings=[];index=0;rate();}focusHeading();};}
function rate(){const idea=matches[index];app.innerHTML=`<span class="eyebrow">Part two · the possibilities</span><h1 tabindex="-1">Does this sound fun?</h1><p>First the activities, then your food stops and ending ideas. Pick the ones you like.</p><div class="meta">IDEA ${index+1} OF ${matches.length} · ${categoryLabel(idea).toUpperCase()}</div><article class="card"><img class="venue-photo" src="${assetUrl(idea.image)}" alt="${escapeHtml(idea.title)}"><span class="eyebrow">${categoryLabel(idea)}</span><h2>${escapeHtml(idea.title)}</h2><p>${escapeHtml(idea.description)}</p>${ideaDetails(idea)}${isSelected('ending','custom')?`<p class="custom-note">Your own ending idea: ${escapeHtml(picks.endingIdea.trim())}</p>`:''}</article><div class="ratings"><button data-rating="pass">×<br>Pass</button><button data-rating="maybe">~<br>Maybe</button><button data-rating="love">♡<br>Sounds fun</button></div><div class="actions"><button class="text-button" id="previous">← ${index===0?'Edit my choices':'Previous idea'}</button></div>`;app.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>{ratings[index]=b.dataset.rating;index++;if(index===matches.length)summary();else rate();focusHeading();});app.querySelector('#previous').onclick=()=>{if(index===0){step=3;build();}else{index--;rate();}focusHeading();};}

function summaryText(){return `Our little plan\n${stages.map(s=>`${s.key}: ${label(s.key)}`).join('\n')}${isSelected('ending','custom')?'\nOwn idea: '+picks.endingIdea.trim():''}${picks.challenge?'\nChallenge: '+(picks.challenge==='ready'?'Be ready to lose':'I am winning'):''}\n\n${matches.map((idea,i)=>`${{love:'Sounds fun',maybe:'Maybe',pass:'Pass'}[ratings[i]]}: ${idea.title}`).join('\n')}`;}
function summary(){const loved=matches.filter((_,i)=>ratings[i]==='love'),maybe=matches.filter((_,i)=>ratings[i]==='maybe');const list=(items,title)=>items.length?`<h2>${title}</h2>${items.map(idea=>`<div class="result result-venue"><img src="${assetUrl(idea.image)}" alt="" loading="lazy"><div><strong>${escapeHtml(idea.title)}</strong><small>${categoryLabel(idea)} &middot; ${escapeHtml(idea.location)}</small></div></div>`).join('')}`:'';app.innerHTML=`<span class="eyebrow">A little plan for the two of us</span><h1 tabindex="-1">${loved.length?'Looks like we have a plan!':'Let us try a few more ideas.'}</h1><p>${loved.length?'Your favorites are picked. Now we just need a day together.':maybe.length?'A few possibilities to think about together.':'Try another combination to find some new possibilities.'}</p>${chips()}<section class="card">${list(loved,'Your favorites')}${list(maybe,'The maybes')}<p>${foodPlan()} ${endingPlan()}</p><p class="notice">Your choices stay here until you refresh or start again. Copy them and send them to me so I can make a plan.</p><button class="primary" id="copy">Copy my choices</button><p id="status" role="status"></p><textarea id="fallback" readonly hidden aria-label="Your choices to copy"></textarea></section><div class="actions"><button class="text-button" id="review">← Review ideas</button><button class="text-button" id="restart">Try another plan</button></div>`;app.querySelector('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(summaryText());app.querySelector('#status').textContent='Copied! Paste this into a message to me.';}catch{const field=app.querySelector('#fallback');field.hidden=false;field.value=summaryText();field.focus();field.select();app.querySelector('#status').textContent='Copy the selected text below to send it to me.';}};app.querySelector('#review').onclick=()=>{index=0;rate();focusHeading();};app.querySelector('#restart').onclick=()=>{step=0;cheekyAttempts=0;picks={};matches=[];ratings=[];index=0;build();focusHeading();};}
build();
